prometheus:
  server:
    ingress:
      enabled: true
      hosts: 
        - prometheus.pf2e.io
      annotations: 
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/auth-type: "basic"
        nginx.ingress.kubernetes.io/auth-secret: "prometheus-basic-auth"
        nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
      tls: 
      - secretName: argocd-secret # do not change, this is provided by Argo CD
        hosts:
          - prometheus.pf2e.io
      persistentVolume: 
        enabled: false

